Repository cendeka/simtpu, pull requests merged in 2022-10, with the labels that each got.

#7 add pdf export: data makam
  app/Http/Controllers/PrintController.php
  composer.json
  composer.lock
  config/app.php
  config/dompdf.php
  resources/views/pages/print/makam.blade.php
  routes/web.php
Labels: enhancement, hacktoberfest-accepted

#9 hiding tanggal dimakamkan
  resources/views/pages/makam/index.blade.php
Labels: bug, enhancement, hacktoberfest-accepted

#12 registrasi avoid null nama_tpu
  resources/views/pages/registrasi/index.blade.php
Labels: bug, hacktoberfest-accepted

#17 redirect to Dashboard after login
  app/Http/Controllers/Auth/LoginController.php
Labels: enhancement, good first issue, hacktoberfest-accepted

#19 avoid null nama_tpu /herregistrasi
  resources/views/pages/herregistrasi/index.blade.php
Labels: bug, enhancement, hacktoberfest-accepted

#24 avoid null registrasi
  resources/views/layouts/topbar.blade.php
  resources/views/pages/registrasi/index.blade.php
Labels: bug, hacktoberfest-accepted

#25 hide menu lock screen on profile
  resources/views/layouts/topbar.blade.php
Labels: bug, hacktoberfest-accepted

#27 bugs fixing Buat Tagihan
  app/Http/Controllers/HerregistrasiController.php
Labels: bug, hacktoberfest-accepted
